### ISSUE TITLE
i have a mod suggestion to add to this

### ISSUE THREAD

**Issue by fnfporterhi** [SanicBTW/PE-0.3.2-Hotfix-ModComp-Reborn#1]
matt wiik 4.... ive always wanted to play the non-effects version of purgatory, plus its a very cool mod, also tko is a good one too

**Comment by SanicBTW** [comment]
alright we will work on it

**Comment by LEVIXDDLMAO** [comment]
i mean maybe- since im working on some shit same with sanic lmao

**Comment by LEVIXDDLMAO** [comment]
i gotta work on bug fixes for my mod and some ports that are private and i gotta fix more shit so yeah and sanic has to work on his engine bugfixes and what not

**Comment by fnfporterhi** [comment]
ok
