### ISSUE TITLE
one other mod

### ISSUE THREAD

**Issue by fnfporterhi** [SanicBTW/PE-0.3.2-Hotfix-ModComp-Reborn#2]
challenge-edd

only cause i just want to prank my friend with eduardo lol

plus i just love the mod i’m a eduardo fanatic

**Comment by SanicBTW** [comment]
uh sure

**Comment by LEVIXDDLMAO** [comment]
> challenge-edd
> 
> only cause i just want to prank my friend with eduardo lol
> 
> plus i just love the mod i’m a eduardo fanatic

you sure do ask for alot lmao

**Comment by SanicBTW** [comment]
yeah lmao but dw man we gotchu, we will work on it

**Comment by LEVIXDDLMAO** [comment]
yup.

**Comment by LEVIXDDLMAO** [comment]
WTH I DiDNT DO ANYTHING

**Comment by fnfporterhi** [comment]
well i’m sorry that i ask for a lot @LEVIXDDLMAO 

thank you for doing that for me guys 😊

**Comment by LEVIXDDLMAO** [comment]
> well i’m sorry that i ask for a lot @LEVIXDDLMAO
> 
> thank you for doing that for me guys 😊

nah im not mad im just saying and np! we will make sure to get these mods done

**Comment by fnfporterhi** [comment]
you guys are the people who get the job done haha

**Comment by LEVIXDDLMAO** [comment]
lol, ( not me working on 5 thing rn )

**Comment by SanicBTW** [comment]
only me 😭

**Comment by LEVIXDDLMAO** [comment]
lol, wdym- im working on 5 things some are private and some are public

**Comment by SanicBTW** [comment]
yeah but im the only one that is workin rn on the mod stuff, its been hours breaking my brain to think of some mod support

**Comment by LEVIXDDLMAO** [comment]
ah i see, i could reright freeplay

**Comment by LEVIXDDLMAO** [comment]
reamake*

**Comment by SanicBTW** [comment]
nah dont worry about it, i though on doin some cool shit like doing a base for each state and then extending them for their respective mods, pretty cool shit

**Comment by LEVIXDDLMAO** [comment]
ooo, cant wait to test it out

**Comment by SanicBTW** [comment]
did you watch the video i posted on the commit chat we were having

**Comment by LEVIXDDLMAO** [comment]
oh yeah of accelernt?

**Comment by SanicBTW** [comment]
yea

**Comment by LEVIXDDLMAO** [comment]
yup

**Comment by SanicBTW** [comment]
pretty cool right

**Comment by fnfporterhi** [comment]
my watch just went 💥

**Comment by fnfporterhi** [comment]
lmao

**Comment by LEVIXDDLMAO** [comment]
> pretty cool right

yup, and sorry

**Comment by fnfporterhi** [comment]
you’re fine

**Comment by fnfporterhi** [comment]
that’s why i have do not disturb

**Comment by LEVIXDDLMAO** [comment]
lollol

**Comment by SanicBTW** [comment]
> my watch just went 💥

lmfaooo

**Comment by LEVIXDDLMAO** [comment]
I need update my page thing lmao

**Comment by SanicBTW** [comment]
what thing

**Comment by fnfporterhi** [comment]
his LEVIXDDLMAO description thing… i think at least

**Comment by SanicBTW** [comment]
ah

**Comment by LEVIXDDLMAO** [comment]
nah for my hank thing

**Comment by LEVIXDDLMAO** [comment]
lol, the page isnt update with the source code

**Comment by LEVIXDDLMAO** [comment]
and i gotta recode tons of shit

**Comment by SanicBTW** [comment]
same

**Comment by LEVIXDDLMAO** [comment]
lol like for bullet notes gotta fix and an update for the sonic thign

**Comment by SanicBTW** [comment]
i think my bullet notes are workin fine

**Comment by LEVIXDDLMAO** [comment]
lol for mine no, since they just play hanks right shoot anim

**Comment by SanicBTW** [comment]
noob

**Comment by LEVIXDDLMAO** [comment]
wow, im trying okay-

**Comment by SanicBTW** [comment]
lmfao i was jokin

**Comment by LEVIXDDLMAO** [comment]
lol, im doing my best, im still trying to push my changes

**Comment by SanicBTW** [comment]
my bad bro

**Comment by LEVIXDDLMAO** [comment]
lol its all good

**Comment by LEVIXDDLMAO** [comment]
i dont wanna sign you out

**Comment by fnfporterhi** [comment]
remember the bullet note test map with like all bullets and spam bullets 😂😂

**Comment by SanicBTW** [comment]
oh yeahhhh that one, i made it to test the bullet code lmao

**Comment by fnfporterhi** [comment]
i still like to try it

**Comment by LEVIXDDLMAO** [comment]
lmao that wasn't hat hard lmao i sfc it

**Comment by SanicBTW** [comment]
i mean it wasnt supposed to be hard, just a test map

**Comment by LEVIXDDLMAO** [comment]
lol,

**Comment by fnfporterhi** [comment]
> lmao that wasn't hat hard lmao i sfc it

uhhhhh excuse me but how


i’ve played osu for 12 years and have basically turned into a fnf pro when it came out… and yet i can’t SFC it cause of the spams.

**Comment by fnfporterhi** [comment]
that*

**Comment by fnfporterhi** [comment]
you know we’ve kept this conversation going for 7 hours lmao

**Comment by LEVIXDDLMAO** [comment]
i have played tons of rthym games not just osu

**Comment by LEVIXDDLMAO** [comment]
step maina and ddr and my fav tbh

**Comment by fnfporterhi** [comment]
osu is how i learned my technical patterns… my spam… and basically almost everything

**Comment by fnfporterhi** [comment]
> step maina and ddr and my fav tbh

STEP MANIA!!!!

**Comment by SanicBTW** [comment]
i started with fnf then went to osu lol

**Comment by SanicBTW** [comment]
i still suck at probably everything

**Comment by LEVIXDDLMAO** [comment]
i like to play 9k crap mainly 4k, and just i type really fast, so that might help

**Comment by fnfporterhi** [comment]
9k is my enemy… it’s the ONE type of mode i can’t fc. 5-7 i can, 8-9-idk how many fnf modders can create i suck at

**Comment by fnfporterhi** [comment]
my friend brags all the time cause he never played osu, but became like the god of multikey

**Comment by LEVIXDDLMAO** [comment]
lol last time i played  9k was when shaggy v2.5 came out

**Comment by SanicBTW** [comment]
my people grew up playing rhythm games tf

**Comment by fnfporterhi** [comment]
last time i played 9k was on osu, i tried a thunderstorm but 9k and i failed halfway

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by fnfporterhi** [comment]
> my people grew up playing rhythm games tf

i grew up with osu, and step mania

**Comment by SanicBTW** [comment]
i grew up watching cartoons and having friends tf

**Comment by LEVIXDDLMAO** [comment]
> my people grew up playing rhythm games tf

 i grew up with alot of rhythm games  guitar hero, i had friends too, lmao

**Comment by SanicBTW** [comment]
but not a dad (you said it yourself on a commit)

**Comment by LEVIXDDLMAO** [comment]
same here

**Comment by SanicBTW** [comment]
imma get back to coding you guys have fun here, cya

**Comment by LEVIXDDLMAO** [comment]
lol, im just charting

**Comment by SanicBTW** [comment]
im trying to do funky mod shit

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by LEVIXDDLMAO** [comment]
have nothing to do anymore

**Comment by SanicBTW** [comment]
wish i could relate

**Comment by LEVIXDDLMAO** [comment]
lol, i was gonna work on video support but idk since nothing really works rn in sory mode

**Comment by SanicBTW** [comment]
a

**Comment by LEVIXDDLMAO** [comment]
ye

**Comment by SanicBTW** [comment]
i think im going to just add all the songs together im doing too much unnecesary work

**Comment by LEVIXDDLMAO** [comment]
ah lol

**Comment by SanicBTW** [comment]
pushed a branch for wip shit

**Comment by LEVIXDDLMAO** [comment]
okay ill look at it

**Comment by LEVIXDDLMAO** [comment]
i think its broken- or something

**Comment by SanicBTW** [comment]
my guy

**Comment by LEVIXDDLMAO** [comment]
no not that

**Comment by SanicBTW** [comment]
you changed the mf git account

**Comment by SanicBTW** [comment]
thats why it shows it was you

**Comment by LEVIXDDLMAO** [comment]
shit sorry, can you change it?

**Comment by LEVIXDDLMAO** [comment]
?

**Comment by SanicBTW** [comment]
im gonna try

**Comment by LEVIXDDLMAO** [comment]
okay, sorry i didnt mean to break anything

**Comment by SanicBTW** [comment]
ok i think its fixed or smth

**Comment by LEVIXDDLMAO** [comment]
ah okay

**Comment by LEVIXDDLMAO** [comment]
![image](https://user-images.githubusercontent.com/92174516/197420229-06ca4f81-2be5-402c-9897-50d2ed48e783.png)
how are we gonna get this to work? Since its using lua

**Comment by SanicBTW** [comment]
lua to haxe easy

**Comment by LEVIXDDLMAO** [comment]
dope, maybe you can show me how to do it

**Comment by SanicBTW** [comment]
actually not easy im going to kill myself ive been doing so many fucking ports from lua to haxe im tired of fucking things up and making them harder i hate everything

**Comment by LEVIXDDLMAO** [comment]
ah

**Comment by LEVIXDDLMAO** [comment]
tbh i just need it for backgrounds

**Comment by SanicBTW** [comment]
im gonna try another way of adding songs to the shit

**Comment by LEVIXDDLMAO** [comment]
ah okay, imma try to make lua to haxe for some cuphead shit

**Comment by LEVIXDDLMAO** [comment]
since i dont know how

**Comment by SanicBTW** [comment]
like reading lua is easy if its properly formatted

**Comment by SanicBTW** [comment]
lets take for example the stage lua from challenge hank folder from the pending folder from the repo

**Comment by SanicBTW** [comment]
```
function onCreate()
	
    makeLuaSprite('city', 'nevada/nevada_city', -600, -100) --the background
		addLuaSprite('city', false);
			setProperty('city.scale.x', getProperty('city.scale.x') + 0.6);
			setProperty('city.scale.y', getProperty('city.scale.y') + 0.2);
	
    makeLuaSprite('stage', 'nevada/nevada_stage', -400, -220); --the stage where everybody sings!
		addLuaSprite('stage', false);
			setProperty('stage.scale.x', getProperty('stage.scale.x') + 0.6);
			setProperty('stage.scale.y', getProperty('stage.scale.y') + 0.8);
		
	if not lowQuality then
		makeLuaSprite('foreground', 'nevada/nevada_foreground', -970, -215); --the foreground, aka tent with the word MADNESS on it
			addLuaSprite('foreground', true);
				setProperty('foreground.scale.x', getProperty('foreground.scale.x') + 0.75);
				setProperty('foreground.scale.y', getProperty('foreground.scale.y') + 0.8);
	
		makeLuaSprite('hill', 'nevada/nevada_hill', -200, 100) --the hill that deimos and sanford occupy.
			addLuaSprite('hill', false);
				setProperty('hill.scale.x', getProperty('hill.scale.x') + 0.8);
				setProperty('hill.scale.y', getProperty('hill.scale.y') + 0.6);
				setLuaSpriteScrollFactor('hill', 0.94, 0.94);
	end
end
```

**Comment by LEVIXDDLMAO** [comment]
hm okay

**Comment by SanicBTW** [comment]
the function onCreate() is executed when the engine calls the lua on the exact time

**Comment by SanicBTW** [comment]
as the lua file we are currently talking about is a stage then you have to go to playstate and the place where you create stages

**Comment by LEVIXDDLMAO** [comment]
so would you remove that?

**Comment by SanicBTW** [comment]
![image](https://user-images.githubusercontent.com/58010536/197420509-8bf5b04d-372b-4665-8483-8a7da5ddd378.png)
here

**Comment by SanicBTW** [comment]
we read the lua file and we analyze it

**Comment by LEVIXDDLMAO** [comment]
ah i see, so for the makeLuaSprite we would have to rename that?

**Comment by SanicBTW** [comment]
``` makeLuaSprite('city', 'nevada/nevada_city', -600, -100) --the background``` 
by reading the FunkinLua.hx file (from newer versions) we can guess that makeLuaSprite its creating a sprite so in haxe it would be like this:
![image](https://user-images.githubusercontent.com/58010536/197420585-a4f01518-644b-429d-9861-5a817e0d6a80.png)

**Comment by SanicBTW** [comment]
wait

**Comment by SanicBTW** [comment]
![image](https://user-images.githubusercontent.com/58010536/197420615-8a1856cc-f5c8-40c9-ac8a-5819d3cf2dd7.png)
this is better

**Comment by LEVIXDDLMAO** [comment]
i see

**Comment by SanicBTW** [comment]
if we keep reading the lua file we can see that ```addLuaSprite('city', false);``` the sprite lua created is being added so thats what the add line does (i forgot what the boolean does there)

**Comment by LEVIXDDLMAO** [comment]
ah, so ill let you know if i sorta got i, and if you need to fix it

**Comment by SanicBTW** [comment]
if we keep reading the lua file (even more) we see this 
![image](https://user-images.githubusercontent.com/58010536/197420650-013086a7-12da-4528-b24e-b665c620f9ee.png)
setProperty changes some property from a lua object in this case a sprite, in haxe it would be like this: 
![image](https://user-images.githubusercontent.com/58010536/197420699-b949582d-0149-4531-bcba-9239843f1660.png)

**Comment by SanicBTW** [comment]
lua is easy if the file you are reading and analyzing is properly formatted and you have a reference of what the functions do (You can open another tab of FunkinLua.hx from your respective Psych Version and search the function throughout the file)

**Comment by LEVIXDDLMAO** [comment]
okay

**Comment by LEVIXDDLMAO** [comment]
got this in

**Comment by SanicBTW** [comment]
you gotta translate it to haxe code

**Comment by LEVIXDDLMAO** [comment]
ik ik, sorry i hid it so ppl cant get your things,

**Comment by fnfporterhi** [comment]
ok so wait send me the link of what website you’re using for this. i wanna try this out on my laptop!

**Comment by fnfporterhi** [comment]
also can you guys use a seperate issue


you’re blowing up my watch

**Comment by SanicBTW** [comment]
> ik ik, sorry i hid it so ppl cant get your things,

password protected remember

**Comment by SanicBTW** [comment]
> also can you guys use a seperate issue
> 
> you’re blowing up my watch

sorry bro

**Comment by LEVIXDDLMAO** [comment]
ah lol, sorry
