### ISSUE TITLE
help-

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SanicBTW/PE-0.3.2-Hotfix-ModComp-Reborn#3]

**Comment by SanicBTW** [comment]
What

**Comment by LEVIXDDLMAO** [comment]
with knife notes T^T

**Comment by SanicBTW** [comment]
Ask help to memehoovy

**Comment by LEVIXDDLMAO** [comment]
he is busy lol

**Comment by LEVIXDDLMAO** [comment]
i cant test anything lmao but i can wait

**Comment by SanicBTW** [comment]
I forgot to map ports on my router you gotta wait the whole day

**Comment by LEVIXDDLMAO** [comment]
thats all good

**Comment by LEVIXDDLMAO** [comment]
i gotta test the double trouble stage

**Comment by SanicBTW** [comment]
Ok lol good luck

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by LEVIXDDLMAO** [comment]
can you turn off the thing or no?

**Comment by SanicBTW** [comment]
> I forgot to map ports on my router you gotta wait the whole day

**Comment by LEVIXDDLMAO** [comment]
ah okay lol i can wait

**Comment by LEVIXDDLMAO** [comment]
its been 3 days lol

**Comment by MemeHoovy** [comment]
> its been 3 days lol

Levi, someone’s stalking me

**Comment by MemeHoovy** [comment]
Look at this https://github.com/ShadowMario/FNF-PsychEngine/issues/11052

**Comment by LEVIXDDLMAO** [comment]
wtf

**Comment by LEVIXDDLMAO** [comment]
reported them

**Comment by MemeHoovy** [comment]
good

**Comment by LEVIXDDLMAO** [comment]
i got you no matter what bud. your like my older brother, ill do anything to help you

**Comment by LEVIXDDLMAO** [comment]
thats what im here for

**Comment by LEVIXDDLMAO** [comment]
memehoovyyyyyyyyyyyyyyyyyyyyyyyyyyy

**Comment by MemeHoovy** [comment]
what?

**Comment by LEVIXDDLMAO** [comment]
hi :D i need help with my FNF-Black-Betrayal

**Comment by LEVIXDDLMAO** [comment]
port

**Comment by MemeHoovy** [comment]
I can’t, I’m away from my pc, and all I have is a shitty old laptop

**Comment by LEVIXDDLMAO** [comment]
ah its just knife notes

**Comment by MemeHoovy** [comment]
yeah, and I can’t really do much

**Comment by LEVIXDDLMAO** [comment]
i see

**Comment by SanicBTW** [comment]
> its been 3 days lol

Bro my bad I totally forgot since I got the cool PC free sorry

**Comment by LEVIXDDLMAO** [comment]
all good

**Comment by SanicBTW** [comment]
Yo my bad power went out for a bit

**Comment by fnfporterhi** [comment]
i got you too bro even if im not your friend ill still help out any way i can (perk of ADHD lmao)
